// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWMatrc.Infrastructure.Persistencia;

#nullable disable

namespace SWMatrc.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SwmatrcDbContext))]
    partial class SwmatrcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWMatrc.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CerradaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CiclosSinRiesgo")
                        .HasColumnType("int");

                    b.Property<int>("ComunidadId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReconocimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fenomeno")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<bool>("Reconocida")
                        .HasColumnType("bit");

                    b.Property<int?>("ReconocidaPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ReglaAlertaId")
                        .HasColumnType("int");

                    b.Property<string>("ReglaNombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Umbral")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("ValorDisparo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("CerradaPorUsuarioId");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.HasIndex("ReconocidaPorUsuarioId");

                    b.HasIndex("ReglaAlertaId");

                    b.HasIndex("SensorId");

                    b.HasIndex("ComunidadId", "FechaCierre")
                        .HasDatabaseName("IX_Alertas_Abiertas")
                        .HasFilter("[FechaCierre] IS NULL");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Bitacora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Accion");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Comunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Poblacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Comunidades", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.EventoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertaId")
                        .HasColumnType("int");

                    b.Property<int>("ComunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fenomeno")
                        .HasColumnType("int");

                    b.Property<int>("NivelMaximo")
                        .HasColumnType("int");

                    b.Property<string>("OrigenSensor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorRegistrado")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("Fenomeno");

                    b.HasIndex("SensorId");

                    b.HasIndex("UsuarioResponsableId");

                    b.HasIndex("ComunidadId", "FechaInicio")
                        .IsDescending(false, true);

                    b.ToTable("EventosHistorial", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Lectura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EstadoSensor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "FechaHora")
                        .IsDescending(false, true);

                    b.ToTable("Lecturas", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.ReglaAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fenomeno")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("TipoSensor", "Activa");

                    b.ToTable("ReglasAlerta", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ComunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UltimaLectura")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UmbralAmarilloAlto")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("UmbralAmarilloBajo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("UmbralNaranjaAlto")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("UmbralNaranjaBajo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("UmbralRojoAlto")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("UmbralRojoBajo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ValorActual")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("VariacionMaxima")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ComunidadId", "Tipo");

                    b.ToTable("Sensores", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("SWMatrc.Domain.Entities.Usuario", "CerradaPorUsuario")
                        .WithMany()
                        .HasForeignKey("CerradaPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SWMatrc.Domain.Entities.Comunidad", "Comunidad")
                        .WithMany("Alertas")
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWMatrc.Domain.Entities.Usuario", "ReconocidaPorUsuario")
                        .WithMany()
                        .HasForeignKey("ReconocidaPorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SWMatrc.Domain.Entities.ReglaAlerta", "ReglaAlerta")
                        .WithMany()
                        .HasForeignKey("ReglaAlertaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SWMatrc.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Alertas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CerradaPorUsuario");

                    b.Navigation("Comunidad");

                    b.Navigation("ReconocidaPorUsuario");

                    b.Navigation("ReglaAlerta");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Bitacora", b =>
                {
                    b.HasOne("SWMatrc.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AccionesRegistradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.EventoHistorial", b =>
                {
                    b.HasOne("SWMatrc.Domain.Entities.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SWMatrc.Domain.Entities.Comunidad", "Comunidad")
                        .WithMany()
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWMatrc.Domain.Entities.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SWMatrc.Domain.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Alerta");

                    b.Navigation("Comunidad");

                    b.Navigation("Sensor");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Lectura", b =>
                {
                    b.HasOne("SWMatrc.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Lecturas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("SWMatrc.Domain.Entities.Comunidad", "Comunidad")
                        .WithMany("Sensores")
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunidad");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Comunidad", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("SWMatrc.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AccionesRegistradas");
                });
#pragma warning restore 612, 618
        }
    }
}
